channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - openalea.lpy
  - openalea.plantgl
  - openalea.widgets
  - tinyobjloader
  - embree
  - make
  - cxx-compiler
  - tinygltf
  - cmake
  - tbb
  - tbb-devel
  - llvm-openmp
  - pip
